Repository conservationtechlab/dencam, pull requests merged in 2024-10, with the labels that each got.

#100 Linting on `recorder.py`
  dencam/recorder.py
Labels: enhancement

#101 Refactor: Make `recorder.BaseRecorder` agnostic to camera type
  dencam.py
  dencam/recorder.py
  dencam/recorder_picamera.py
Labels: enhancement

#104 80 solar label hardcoded
  README.md
  dencam/example_config.yaml
  dencam/mppt.py
Labels: geeksquad

#106 Refactor and lint main dencam module
  dencam.py
Labels: enhancement, geeksquad
